#pragma once

#define SYSCALL_WRITE 1
#define SYSCALL_READ 2
#define SYSCALL_OPEN 3
#define SYSCALL_CLOSE 4
#define SYSCALL_EXIT 5
#define SYSCALL_GETDENTS 6
#define SYSCALL_FORK 7
#define SYSCALL_EXEC 8
#define SYSCALL_WAITPID 9
#define SYSCALL_GETPID 10
#define SYSCALL_SBRK 11
#define SYSCALL_GETCWD 12
#define SYSCALL_CHDIR 13
#define SYSCALL_DUP2 14
#define SYSCALL_PIPE 15
#define SYSCALL_MKDIR 16
#define SYSCALL_RMDIR 17
#define SYSCALL_UNLINK 18
#define SYSCALL_YIELD 24