ARCH=i386

# Toolchain
CC = i686-elf-gcc
LD = i686-elf-ld
AS = nasm

# Global Paths (Adjust these to your project layout)
# We use $(abspath) to ensure paths work regardless of which subfolder we are in
USER_DIR := $(abspath $(dir $(lastword $(MAKEFILE_LIST))))
PROJECT_ROOT := $(abspath $(USER_DIR)/..)
BUILD_ROOT := $(PROJECT_ROOT)/build/$(ARCH)
USER_BUILD_ROOT   := $(BUILD_ROOT)/user

BIN_DIR=$(USER_BUILD_ROOT)/bin

LIB_BUILD_DIR := $(USER_BUILD_ROOT)/lib
LIB_ARCHIVE := $(LIB_BUILD_DIR)/libuser.a

CRT0     := $(USER_BUILD_ROOT)/crt0.o
LIBSYS   := $(BUILD_ROOT)/libc/libc.a

# Flags
# -MMD -MP creates dependency files so changing a .h triggers a recompile
CFLAGS  = -ffreestanding -O2 -Wall -Wextra -I$(PROJECT_ROOT)/include -I$(USER_DIR)/include -MMD -MP
LDFLAGS = -nostdlib -ffreestanding -lgcc -T $(USER_DIR)/linker.ld